services:
    an602.skeleton.command.create:
        class: an602\skeleton\console\create
        arguments:
            - '@user'
            - '@language'
            - '@an602.skeleton.helper.packager'
            - '@an602.skeleton.helper.validator'
        tags:
            - { name: console.command }
