services:
# ----- Cron tasks -----
    an602.viglink.cron.task.viglink:
        class: an602\viglink\cron\viglink
        arguments:
            - '@config'
            - '@an602.viglink.helper'
        calls:
            - [set_name, [cron.task.viglink]]
        tags:
            - { name: cron.task }
