services:
    installer.navigation.provider:
        class: an602\install\helper\navigation\navigation_provider
        arguments:
            - '@installer.navigation.service_collection'

    installer.navigation.service_collection:
            class: an602\di\service_collection
            arguments:
                - '@service_container'
            tags:
                - { name: service_collection, tag: installer.navigation }

    installer.navigation.main_navigation:
        class: an602\install\helper\navigation\main_navigation
        shared: false
        tags:
            - { name: installer.navigation }

    installer.navigation.install_navigation:
        class: an602\install\helper\navigation\install_navigation
        arguments:
            - '@installer.helper.install_helper'
        shared: false
        tags:
            - { name: installer.navigation }

    installer.navigation.update_navigation:
        class: an602\install\helper\navigation\update_navigation
        arguments:
            - '@installer.helper.install_helper'
        shared: false
        tags:
            - { name: installer.navigation }

    installer.navigation.convertor_navigation:
        class: an602\install\helper\navigation\convertor_navigation
        arguments:
            - '@installer.helper.install_helper'
        shared: false
        tags:
            - { name: installer.navigation }
