imports:
    - { resource: services_installer.yml }
    - { resource: ../../default/container/services_event.yml }
    - { resource: ../../default/container/services_filesystem.yml }
    - { resource: ../../default/container/services_http.yml }
    - { resource: ../../default/container/services_language.yml }
    - { resource: ../../default/container/services_php.yml }
    - { resource: ../../default/container/services_routing.yml }
    - { resource: ../../default/container/services_twig.yml }

services:
    cache.driver:
        class: '%cache.driver.class%'
        arguments:
            - '%core.cache_dir%'

    config:
        class: an602\config\config
        arguments:
            -
                rand_seed: 'installer_seed'
                rand_seed_last_update: 0

    controller.resolver:
        class: an602\controller\resolver
        arguments:
            - '@service_container'
            - '%core.root_path%'
            - '@template'

    file_locator:
        class: an602\routing\file_locator
        arguments:
            - '@filesystem'
            - '%core.root_path%'

    kernel_exception_subscriber:
        class: an602\install\event\kernel_exception_subscriber
        arguments:
            - '@an602.installer.controller.helper'
            - '@language'
            - '@template'
        tags:
            - { name: kernel.event_subscriber }

    language.loader:
        parent: language.loader_abstract

    path_helper:
        class: an602\path_helper
        arguments:
            - '@symfony_request'
            - '@filesystem'
            - '@request'
            - '%core.root_path%'
            - '%core.php_ext%'

    routing.resources_locator.default:
        class: an602\routing\resources_locator\installer_resources_locator
        arguments:
            - '@filesystem'
            - '%core.root_path%'
            - '%core.environment%'
        tags:
            - { name: routing.resources_locator }

    template:
        class: an602\template\twig\twig
        arguments:
            - '@path_helper'
            - '@config'
            - '@template_context'
            - '@template.twig.environment'
            - '%core.template.cache_path%'
            - null
            - '@template.twig.extensions.collection'

    template.twig.environment:
        class: an602\template\twig\environment
        arguments:
            - '@config'
            - '@filesystem'
            - '@path_helper'
            - '%core.template.cache_path%'
            - null
            - '@template.twig.loader'
            - null
            - []
        calls:
            - [setLexer, ['@template.twig.lexer']]

    user:
        class: an602\user
        arguments:
            - '@language'
            - '%datetime.class%'

    console.exception_subscriber:
        class: an602\console\exception_subscriber
        arguments:
            - '@language'
            - '%debug.exceptions%'
        tags:
            - { name: kernel.event_subscriber }
